# Generated by Django 2.2.3 on 2019-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idjuego', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('puntos', models.IntegerField()),
                ('intentos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('idjuego', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('gpartida', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fnacimiento', models.DateField()),
                ('comentarios', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('nombreusuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=20)),
            ],
        ),
    ]
